kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-production
  labels:
    type: local
    env: production
spec:
  storageClassName: generic
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo-production"
