apiVersion: v1
kind: Service
metadata:
  name: spacemissions-api
  namespace: production
  labels:
    app: spacemissions-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
  selector:
    app: spacemissions-api-pod
  type: NodePort
